language: objective-c
osx_image: xcode9
script:
  - xcodebuild clean test -project RegexUtil.xcodeproj -scheme RegexUtil-macOS -destination "platform=OS X" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
  
